### ISSUE TITLE
Request from$50 of Google Cloud Education Grant

### ISSUE THREAD

**Issue by gcordova19** [mcv-m6-video/mcv-m6-2020-team3#7]
![image](https://user-images.githubusercontent.com/15816428/76141101-63c26580-6061-11ea-8324-e4519e9f45b7.png)

Hi, I have followed the link from the presentation [MCV-M6-1819] Google Cloud Platform
(page 2) and I got some message related invalid course.

Message: 

Invalid Course
Coupons cannot be retrieved for this course. Please contact your course instructor for further help.

Can I do something to have access?

**Comment by xavigiro** [comment]
Hi Gabriela, have her [the right link](https://google.secure.force.com/GCPEDU?cid=kIy7TKDm3%2F6yvxGKPkjse9WfwzVvBPJhZm%2F6cCqo6P2XuyeIyUWpuUhtAZRwZs%2Fd).

The problem here is that we did not update the link to the [Google Cloud Platform instructions](https://docs.google.com/presentation/d/1XvzE-Jz5RFYybMQ-qHp3XUzl5cv8L6FkXQfEg5tjqc4/edit?usp=sharing) in the Project presentation. This is fixed now. Please check them out.

**Comment by xavigiro** [comment]
Please close the issue if you can access to the form now. Cheers !
